---
driver:
  provision: true

provisioner:
  name: puppet_apply
  manifests_path: manifests
  manifest: local.pp
  modules_path: modules
  hiera_data_path: data
  hiera_deep_merge: true
  puppet_verbose: true
  puppet_debug: false
  require_chef_for_busser: false
  require_puppet_repo: false
  custom_options: '--show_diff'
  verify_host_key: false

transport:
  name: sftp

busser:
  ruby_bindir: /usr/bin

platforms:
  - name: ubuntu-puppet-jenkins
    driver_plugin: vagrant
    driver:
      vagrantfile_erb: vagrantfiles/Vagrantfile-debianoid.erb
      box: ubuntu/bionic64
      box_url: https://app.vagrantup.com/ubuntu/boxes/bionic64
      customize:
        memory: 1024
      synced_folders:
        - ['./files', '/tmp/files']
      network:
        - ["forwarded_port", {guest: 80, host: 80}]
        - ["forwarded_port", {guest: 443, host: 443}]
        #- ['private_network', {ip: '192.168.33.33'}]
    # vagrant automatically generates a hostname, if that exceeds 64 characters vbox fails, see bug #6
suites:
  - name: default

